# If you want to make sidebar border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "catppuccin-macchiato"

# ========= Border =========
file_panel_border = "#535b68" # Overlay0
sidebar_border = "#1f2a35"    # Base
footer_border = "#535b68"     # Overlay0

# ========= Border Active =========
file_panel_border_active = "#a980c4" # Lavendar
sidebar_border_active = "#f77172"    # Red
footer_border_active = "#65a884"     # Green
modal_border_active = "#393c4d"      # Overlay2

# ========= Background (bg) =========
full_screen_bg = "#1f2a35" # Base
file_panel_bg = "#1f2a35"  # Base
sidebar_bg = "#1f2a35"     # Base
footer_bg = "#1f2a35"      # Base
modal_bg = "#1f2a35"       # Base

# ========= Foreground (fg) =========
full_screen_fg = "#a5adcb" # Subtext0
file_panel_fg = "#a5adcb"  # Subtext0
sidebar_fg = "#a5adcb"     # Subtext0
footer_fg = "#a5adcb"      # Subtext0
modal_fg = "#a5adcb"       # Subtext0

# ========= Special Color =========
cursor = "#f77172"  # Rosewater
correct = "#65a884" # Green
error = "#f77172"   # Red
hint = "#74add2"    # Sapphire
cancel = "#f77172"  # Maroon

# Gradient color can only have two color!
gradient_color = ["#74add2", "#a980c4"] # [Blue, Mauve]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#65a884" # Green
file_panel_top_path = "#74add2"           # Blue
file_panel_item_selected_fg = "#74add2"   # Sky
file_panel_item_selected_bg = "#1f2a35"   # Base

# ========= Sidebar Special Items =========
sidebar_title = "#74add2"            # Sapphire
sidebar_item_selected_fg = "#74add2" # Sky
sidebar_item_selected_bg = "#1f2a35" # Base
sidebar_divider = "#393c4d"          # Overlay2

# ========= Modal Special Items =========
modal_cancel_fg = "#1d232e" # Surface0
modal_cancel_bg = "#f77172" # Maroon

modal_confirm_fg = "#1d232e" # Surface0
modal_confirm_bg = "#74add2" # Sky

# ========= Help Menu =========
help_menu_hotkey = "#74add2" # Sky
help_menu_title = "#f77172"  # Maroon
