# More details are at https://superfile.netlify.app/configure/superfile-config/

# Change your theme
theme = 'hush'

editor = "" # The editor files will be opened with. (Leave blank to use the EDITOR environment variable).
dir_editor = "" # The editor directories will be opened with. (Leave blank to use the default editors).

auto_check_update = true
cd_on_quit = false # https://superfile.netlify.app/configure/superfile-config/#cd_on_quit
default_open_file_preview = false # Whether to open file preview automatically every time superfile is opened.
show_image_preview = true # Whether to show image preview

show_panel_footer_info = true # Whether to hide additional footer info for file panel.
default_directory = "." # The path of the first file panel when superfile is opened.
file_size_use_si = false # Display file sizes using powers of 1000 (kB, MB, GB) instead of powers of 1024 (KiB, MiB, GiB).
default_sort_type = 0 # Default sort type (0: Name, 1: Size, 2: Date Modified, 3: Type).
sort_order_reversed = false # Default sort order (false: Ascending, true: Descending).
case_sensitive_sort = false # Case sensitive sort by name (upper "B" comes before lower "a" if true).
shell_close_on_success = false # Whether to exit the shell on successful command execution.
debug = false # Whether to enable debug mode.

code_previewer = 'bat' # Whether to use the builtin syntax highlighting with chroma or use bat. Values: "" for builtin chroma, "bat" for bat
nerdfont = true # If you don't have or don't want Nerdfont installed you can turn this off
transparent_background = false # Set transparent background or not (this only work when your terminal background is transparent)
file_preview_width = 0 # File preview width allow '0' (this mean same as file panel),'x' x must be from 2 to 10 (This means that the width of the file preview will be one xth of the total width.)
sidebar_width = 20 # The length of the sidebar. If you don't want to display the sidebar, you can input 0 directly. If you want to display the value, please place it in the range of 3-20.

# Border style (' ' for borderless)
border_top = '─'
border_bottom = '─'
border_left = '│'
border_right = '│'
border_top_left = '╭'
border_top_right = '╮'
border_bottom_left = '╰'
border_bottom_right = '╯'
border_middle_left = '├'
border_middle_right = '┤'

metadata = false # Show more detailed metadata, please install exiftool before enabling this plugin!
enable_md5_checksum = false # Enable MD5 checksum generation for files
