# Global hotkeys (cannot conflict with other hotkeys)
confirm = ['enter', 'right', 'l']
quit = ['q', 'esc']

# Movement
list_up = ['up', 'k']
list_down = ['down', 'j']
page_up = ['ctrl+u', '']
page_down = ['ctrl+d', '']

# File panel control
create_new_file_panel = ['A', '']
close_file_panel = ['w', '']
next_file_panel = ['L', '']
previous_file_panel = ['H', '']
toggle_file_preview_panel = ['f', '']
open_sort_options_menu = ['o', '']
toggle_reverse_sort = ['R', '']

# Change focus
focus_on_process_bar = ['P', '']
focus_on_sidebar = ['S', '']
focus_on_metadata = ['M', '']

# Create file/directory and rename
file_panel_item_create = ['a', '']
file_panel_item_rename = ['r', '']

# File operations
copy_items = ['y', '']
cut_items = ['x', '']
paste_items = ['p', '']
delete_items = ['d', '']

# Compress and extract
extract_file = ['ctrl+e', '']
compress_file = ['ctrl+a', '']

# Editor
open_file_with_editor = ['e', '']
open_current_directory_with_editor = ['E', '']

# Other
pinned_directory = ['ctrl+p', '']
toggle_dot_file = ['.', '']
change_panel_mode = ['v', '']
open_help_menu = ['?', '']
open_command_line = [':', '']
open_spf_prompt = ['>', '']
copy_path = ['ctrl+y', '']
copy_present_working_directory = ['c', '']
toggle_footer = ['F', '']

# Typing hotkeys (can conflict with all hotkeys)
confirm_typing = ['enter', '']
cancel_typing = ['ctrl+c', 'esc']

# Normal mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
parent_directory = ['h', 'left', 'backspace']
search_bar = ['/', '']

# Select mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
file_panel_select_mode_items_select_down = ['J', '']
file_panel_select_mode_items_select_up = ['K', '']
file_panel_select_all_items = ['A', '']
