gui:
    mouseEvents: false
    sidePanelWidth: 0.3

    theme:
        activeBorderColor:
            - '#74add2'
            - bold

        inactiveBorderColor:
            - '#6c7077'

        selectedLineBgColor:
            - '#121c26'
            - bold

    showIcons: true
    nerdFontsVersion: '3'
    showFileIcons: true

    border: 'rounded'
