"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
continuation_prompt = "[▸▹ ](dimmed white)"

format = """
$hostname\
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$character"""

right_format = """
$localip\
$shlvl\
$shell\
$env_var\
$jobs\
$sudo\
$username\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$status\
$cmd_duration"""


[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
truncation_length = 0
truncation_symbol = ''


[git_branch]
format = '[$symbol $branch(:$remote_branch)]($style) '
symbol = ''


[git_status]
format = '[$all_status$ahead_behind]($style)'

conflicted = '[ $count ](bold red)'
stashed = '[󰆓 $count ](bold yellow)'
deleted = '[󰇾 $count ](bold red)'
renamed = '[ $count ](bold cyan)'
modified = '[ $count ](bold cyan)'
typechanged = ''
staged = '[󰏫 $count ](bold green)'
untracked = '[ $count ](bold purple)'

diverged = '⇕ '
ahead = '[ $count ](bold blue)'
behind = '[ $count ](bold blue)'
up_to_date = ''


[username]
format = '[$user]($style) • '
show_always = false

[username.aliases]
root = "󰆥"
