"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"
palette = 'hush'


format = """
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$character\
"""

right_format = """
$package\

$localip\
$shlvl\
$shell\
$env_var\
$jobs\
$sudo\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$hg_branch\
$pijul_channel\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$erlang\
$fennel\
$guix_shell\
$haxe\
$helm\
$kotlin\
$lua\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$raku\
$rlang\
$red\
$ruby\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$status\

$c\
$docker_context\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$julia\
$nodejs\
$python\
$rust\
$scala\

$cmd_duration\
$username\
"""


[palettes.hush]
c = '#699DD3'
cmd_duration = '#65A884'
docker = '#1D63ED'
elixir = '#9F8FAF'
elm = '#E79F00'
golang = '#00ADD8'
gradle = '#29DB2E'
haskell = '#93548F'
julia = '#5369B1'
lua = '#080884'
nodejs = '#417E38'
package = '#535B68'
python = '#F7E170'
rust = '#B7410E'
scala = '#DE3423'
username = '#393C4D'

black = '#121C26'
bright_black = '#7E848E'
red = '#F77172'
green = '#65A884'
yellow = '#CEC999'
blue = '#74ADD2'
magenta = '#A980C4'
cyan = '#2D949F'
white = '#FFFFFF'


[aws]
format = ' [$symbol ( $profile)( $region)( \[$duration\])]($style) '
style = 'bold fg:yellow'
symbol = '󰸏'


[c]
format = ' [$symbol ( $version)]($style) '
style = 'bold fg:c'
symbol = ''


[cmd_duration]
format = ' [󰥔  $duration]($style) '
style = 'bold fg:cmd_duration'


[directory]
format = '[$path]($style)[( $read_only)]($read_only_style) '
truncation_length = 0
truncation_symbol = ''
read_only = ''


[docker_context]
format = ' [$symbol ( $version)]($style) '
style = 'bold fg:docker'
symbol = '󰡨'


[elixir]
format = ' [$symbol ( $version)]($style) '
style = 'bold fg:elixir'
symbol = ''


[elm]
format = ' [$symbol ( $version)]($style) '
style = 'bold fg:elm'
symbol = ''


[git_branch]
format = '[$symbol $branch(:$remote_branch)]($style) '
symbol = ''


[git_status]
format = '[$ahead_behind$all_status]($style)'

diverged = '⇕ '
ahead = '[ $count ](bold blue)'
behind = '[ $count ](bold blue)'
up_to_date = ''

conflicted = '[ $count ](bold red)'
stashed = '[󰆓 $count ](bold yellow)'
deleted = '[󰇾 $count ](bold red)'
renamed = '[ $count ](bold cyan)'
modified = '[ $count ](bold cyan)'
typechanged = ''
staged = '[󰏫 $count ](bold green)'
untracked = '[ $count ](bold purple)'


[golang]
format = ' [$symbol ( $version)]($style) '
style = 'bold fg:golang'
symbol = ''


[gradle]
format = ' [$symbol ( $version)]($style) '
style = 'bold fg:gradle'
symbol = ''


[haskell]
format = ' [$symbol ( $version)]($style) '
style = 'bold fg:haskell'
symbol = ''


[hostname]
format = '[$hostname]($style) :: '
style = 'bold fg:green'


[julia]
format = ' [$symbol ( $version)]($style) '
style = 'bold fg:julia'
symbol = ''


[lua]
format = ' [](fg:bright_black)[$symbol ( $version)]($style)[](fg:bright_black) '
style = 'bold fg:lua bg:bright_black'
symbol = ''


[nodejs]
format = ' [$symbol ( $version)]($style) '
style = 'bold fg:nodejs'
symbol = '󰎙'


[package]
format = ' [($version)]($style) '
style = 'bold fg:package'
symbol = ''


[python]
format = ' [$symbol ( $version)]($style) '
style = 'bold fg:python'
symbol = ''


[rust]
format = ' [$symbol ( $version)]($style) '
style = 'bold fg:rust'
symbol = ''


[scala]
format = ' [$symbol ( $version)]($style) '
style = 'bold fg:scala'
symbol = ''


[username]
format = ' [](fg:username)[$user]($style)[](fg:username)'
style_root = 'bold fg:white bg:username'
style_user = 'bold fg:white bg:username'
show_always = true

[username.aliases]
root = " 󰆥 "
