"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"
palette = 'hush'


format = """
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$character\
"""

right_format = """
$localip\
$shlvl\
$shell\
$env_var\
$jobs\
$sudo\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$status\

$golang\
$nodejs\

$cmd_duration\
$username\
"""


[palettes.hush]
cmd_duration = '#65A884'
golang = '#00ADD8'
nodejs = '#417E38'
username = '#393C4D'

black = '#121C26'
red = '#F77172'
green = '#65A884'
yellow = '#CEC999'
blue = '#74ADD2'
magenta = '#A980C4'
cyan = '#2D949F'
white = '#FFFFFF'


[cmd_duration]
format = ' [󰥔 $duration]($style) '
style = 'bold fg:cmd_duration'


[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
truncation_length = 0
truncation_symbol = ''


[git_branch]
format = '[$symbol $branch(:$remote_branch)]($style) '
symbol = ''


[git_status]
format = '[$ahead_behind$all_status]($style)'

diverged = '⇕ '
ahead = '[ $count ](bold blue)'
behind = '[ $count ](bold blue)'
up_to_date = ''

conflicted = '[ $count ](bold red)'
stashed = '[󰆓 $count ](bold yellow)'
deleted = '[󰇾 $count ](bold red)'
renamed = '[ $count ](bold cyan)'
modified = '[ $count ](bold cyan)'
typechanged = ''
staged = '[󰏫 $count ](bold green)'
untracked = '[ $count ](bold purple)'


[golang]
format = ' [$symbol ($version)]($style) '
style = 'bold fg:golang'
symbol = ''


[nodejs]
format = ' [$symbol ($version)]($style) '
style = 'bold fg:nodejs'
symbol = '󰎙'


[username]
format = '[](fg:username)[$user]($style)[](fg:username)'
style_root = 'bold fg:white bg:username'
style_user = 'bold fg:white bg:username'
show_always = true

[username.aliases]
root = "󰆥"
