[colors.primary]
foreground = "#ffffff"
background = "#1d232e"

[colors.normal]
black = "#000000"
red = "#f77172"
green = "#65a884"
yellow = "#cec999"
blue = "#74add2"
magenta = "#a980c4"
cyan = "#2d949f"
white = "#ffffff"

[colors.bright]
black = "#8e9197"
red = "#f77172"
green = "#65a884"
yellow = "#cec999"
blue = "#74add2"
magenta = "#a980c4"
cyan = "#2d949f"
white = "#ffffff"
